### ISSUE TITLE
[Feature Request] `--exclude` parameter

### ISSUE THREAD

**Issue by Archmonger** [rtts/djhtml#48]
Currently running into some issues where djhtml is formatting my `mkdocs` documentation directory, causing unnecessary html code modifications.

Ideally I'd like to be able to exclude my `./docs/*` to prevent that.

**Comment by JaapJoris** [comment]
Hi there, and thanks for your suggestion!

I think the following pre-commit config will accomplish what you want:

```yaml
repos:
- repo: https://github.com/rtts/djhtml
  rev: 'main'  # replace with the latest tag on GitHub
  hooks:
    - id: djhtml
      exclude: ^docs/
```

Could you try this and see if it works?
