### ISSUE TITLE
Charset error with fontello / emoji scss file

### ISSUE THREAD

**Issue by GitRon** [rtts/djhtml#72]
Hi @JaapJoris 

I run your linter against some old code base having a fontello SCSS file.

It fails with:

> Error: 'charmap' codec can't decode byte 0x81 in position 1940: character maps to <undefined>

I can't attach the file here, so I try to paste a relevant part of it here:

````scss

.icon-x-alarm:before { content: '\e800'; } /* '' */
.icon-x-align-center:before { content: '\e801'; } /* '' */

````

![grafik](https://user-images.githubusercontent.com/3176075/216565987-cd6e2228-081d-407f-9991-e07529ecca75.png)

The file is formatted as UTF-8.

I just excluded this file but maybe worth looking into...

Thx!
Ronny
