### ISSUE TITLE
Broken indention for scss files

### ISSUE THREAD

**Issue by GitRon** [rtts/djhtml#81]
Hi @JaapJoris 

I have a scss file with multiple declarations beneith each other:

````scss
.icon-x-alarm:before { content: '\e800'; } /* '' */
.icon-x-align-center:before { content: '\e801'; } /* '' */
.icon-x-align-justify:before { content: '\e802'; } /* '' */
.icon-x-align-left:before { content: '\e803'; } /* '' */
.icon-x-align-right:before { content: '\e804'; } /* '' */
.icon-x-anchor:before { content: '\e805'; } /* '' */
````

What the linter does is this:

![grafik](https://user-images.githubusercontent.com/3176075/220841561-6e94f7e3-b3e1-41e1-9338-c02471fd3e60.png)

But that's the only bug I found so far 💪 

Best from Cologne
Ronny

**Comment by JaapJoris** [comment]
Hi Ronny, and thank you for reporting this. This bug is actually worse than it seems: string detection in CSS mode is done "greedily", so that the following:

```css
.icon1:before { content:'foo'} .icon2:before { content:'bar'}
```

incorrectly leads to the substring `'foo'} .icon2:before { content:'bar'` being detected as an entire string (because it is technically the largest substring surrounded by quotes).

This was already fixed for DjJS mode, and I'll now also fix it for DjCSS mode and create a new release. Thanks again for noticing this so quickly!

**Comment by GitRon** [comment]
Thx for fixing it that quickly! When will you release the bugfix?

**Comment by GitRon** [comment]
It works 💪

**Comment by DmytroLitvinov** [comment]
I am using `main` branch in pre-commit and we are having also strangle indentation in scss files.

Initial scss code:
```
$line-height:           1.5 !default; // calculating line-height: round($font-size * 1.5)
$line-space:            10px !default;
```

And how it indented:
```
$line-height:           1.5 !default; // calculating line-height: round($font-size * 1.5)
                                                                  $line-space:            10px !default;
```

Another one:
```
  // START: Quick dirty fix for Boostrap alert
  .alert {
    position: relative;
    padding: 0.75rem 1.25rem;
    margin-bottom: 1rem;
    border: 0 solid transparent;
    border-radius: 0;
```

And result:
```
  // START: Quick dirty fix for Boostrap alert
            .alert {
    position: relative;
    padding: 0.75rem 1.25rem;
    margin-bottom: 1rem;
    border: 0 solid transparent;
    border-radius: 0;
```

Seems like the issue somewhere with comments

**Comment by DmytroLitvinov** [comment]
Adn this one is also strange:
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/16066485/221540394-b7d19f27-37de-4ef9-827b-f483152fe1bd.png">

**Comment by DmytroLitvinov** [comment]
here is more information how it affects.

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/16066485/221541406-0ac75a2c-7fa6-4f8a-8836-fd08ba6aabe9.png">
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/16066485/221541513-42fe4395-9872-488d-94ad-7e8f0c803c0b.png">
<img width="979" alt="image" src="https://user-images.githubusercontent.com/16066485/221541655-bdd2a34d-ecee-4ada-ad56-175192117166.png">
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/16066485/221541702-c07fa5ea-0e0a-4675-920c-2f713563323a.png">

**Comment by JaapJoris** [comment]
Thanks for reporting these bugs. They all stem from the problem that my understanding of SCSS and, by extension, DjCSS's understanding is limited. The first bug you reported is caused by DjCSS not being aware that `//` starts a comment. The following:

```css
div {
    foo: bar; // comment: ignore
    font-weight: bold;
}
```

therefore gets indented as this:

```css
div {
    foo: bar; // comment: ignore
                          font-weight: bold;
}
```

Because DjCSS thinks that `comment:` is a CSS attribute without the trailing `;`. Adding one fixes it:

```css
div {
    foo: bar; // comment: ignore;
    font-weight: bold;
}
```

The second problem is that DjCSS treats text between `(` and `)` no different than ordinary attribute/value pairs in CSS. Note that the following:

```css
@font-face {
    src: url('Arial.woff2') format('woff2'),
         url('Arial.woff') format('woff');
}
```

is consistent with the following, from DjCSS's perspective:

```css
@include button-outline-variant(
    $color: $white,
            $hover-background;
)
```

This is a harder problem, but I think it can be fixed by special-casing stuff between `(` and `)`.

Are there any further SCSS peculiarities that I'm not yet aware of?
