### ISSUE TITLE
SCSS file wrong idention with @font-face

### ISSUE THREAD

**Issue by GitRon** [rtts/djhtml#90]
Hi @JaapJoris 

I updated to the 3.0.4 version and now get this odd behaviour 😅 

```scss
@font-face {
  font-family: 'proxima nova light';
  src: url(static://fonts/proxima-nova-light.otf);
  }

       @font-face {
    font-family: 'proxima nova s';
    src: url(static://fonts/ProximaNovaS-Bold.eot);
      src: url(static://fonts/ProximaNovaS-Bold.eot?#iefix) format('embedded-opentype'),
        url(static://fonts/ProximaNovaS-Bold.woff2) format('woff2'),
          url(static://fonts/ProximaNovaS-Bold.woff) format('woff'),
            url(static://fonts/ProximaNovaS-Bold.ttf) format('truetype'),
              url(static://fonts/ProximaNovaS-Bold.svg#ProximaNovaS-Bold) format('svg');
                font-weight: bold;
                font-style: normal;
              }

```

![grafik](https://user-images.githubusercontent.com/3176075/223656444-e9f531fd-2981-485b-98c4-d352e9dd338e.png)

Best from Cologne  
Ronny

**Comment by JaapJoris** [comment]
Hi there. Could you please, _please_, not post screenshots of text, but the text instead?

**Comment by GitRon** [comment]
Haha, sorry, wanted to point out the difference. Will add the code tomorrow.

**Comment by GitRon** [comment]
Updated my post. 👍

**Comment by JaapJoris** [comment]
Thanks, I see now what the problem is. DjCSS interprets the everything following the `//` as a comment:

```css
@font-face {
  font-family: 'proxima nova light';
  src: url(static: // fonts/proxima-nova-light.otf);
  }
```

Enclosing the URL in quotes fixes this:

```css
@font-face {
  font-family: 'proxima nova light';
  src: url('static://fonts/proxima-nova-light.otf');
}
```

Nevertheless, I'll add an exception to not treat `//` inside URLs as comments.
