### ISSUE TITLE
html comment lines not indented

### ISSUE THREAD

**Issue by minusf** [rtts/djhtml#98]
it seems that html comment lines are not indented:

```
<p>
    <!-- some comment -->
</p>
```

```
-   repo: https://github.com/rtts/djhtml
    rev: '3.0.6'
    hooks:
      - id: djhtml
        entry: djhtml --tabwidth 2
```
